/** The source of the sample */
export enum SampleSource {
    TUMOUR = 'TUMOUR',
    BONE_MARROW_ASPIRATE_TUMOUR_SORTED_CELLS = 'BONE_MARROW_ASPIRATE_TUMOUR_SORTED_CELLS',
    BONE_MARROW_ASPIRATE_TUMOUR_CELLS = 'BONE_MARROW_ASPIRATE_TUMOUR_CELLS',
    BLOOD = 'BLOOD',
    SALIVA = 'SALIVA',
    FIBROBLAST = 'FIBROBLAST',
    TISSUE = 'TISSUE'
};
